# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"    # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

# Wait 10 milliseconds for starship to check files under the current directory.
# scan_timeout = 60

# [line_break]
# disabled = true

[directory]
style = "bold blue"

# [cmd_duration]
# format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
